from faker                import Faker
from app.schemas.usuarios import UsuarioBase
from app.schemas.empresas import EmpresaBase
from app.schemas.kpis     import KpiBase
from app.schemas.metricas import Metrica

fake = Faker("pt_BR")  # opcional: usar contexto do Brasil

def create_fake_usuario():
    return UsuarioBase(
        id = None,
        login = fake.user_name(),
        senha = fake.password(length=8),
        nome_completo = fake.name(),
        empresa_id = fake.random_int(min=1, max=100),
        email = fake.email(),
        dt_criacao = None,
        ativo = True,
        dt_atualizacao = None,
        ultimo_login = None,
    )

def create_fake_empresa():
    return EmpresaBase(
        id=None,
        cnpj=fake.cnpj(),
        cnes=fake.random_int(min=1000000, max=9999999),
        razao=fake.company(),
        fantasia=fake.company_suffix(),
        cep=fake.postcode(),
        numero_endereco=fake.building_number(),
        site=fake.url(),
        telefone=fake.phone_number(),        
        email=fake.company_email(),
        dt_criacao=None,        
        ativo=True,        
        dt_atualizacao=None,
    )

def create_fake_kpi():
    return KpiBase(
        titulo=fake.catch_phrase(),
        descricao=fake.text(max_nb_chars=100),
        dominio=fake.word(),
        unidade=fake.random_element(elements=["%", "/1000 pacientes-dia", "Número absoluto"]),
        meta=round(fake.pyfloat(left_digits=2, right_digits=1, min_value=0, max_value=100)),
        meta_descricao=fake.sentence(),
        sequencia=fake.random_int(min=1, max=10),
        direcao_favoravel=fake.random_element(elements=["C", "D"]),
        caminho_documentacao=fake.url(),
        ativo=True,
        dt_criacao=None,
        dt_atualizacao=None,
    )

def create_fake_metricas():
    return Metrica(
        cnes=fake.random_int(min=1000000, max=9999999),
        ano=fake.year(),
        mes=fake.month(),
        partos_vag=fake.random_int(min=0, max=100),
        partos_ces=fake.random_int(min=0, max=100),
        cli_sai_ant=fake.random_int(min=0, max=100),
        cli_reint=fake.random_int(min=0, max=100),
        cir_sai_ant=fake.random_int(min=0, max=100),
        cir_reint=fake.random_int(min=0, max=100),
        pac_dia=fake.random_int(min=0, max=100),
        pcr_eventos=fake.random_int(min=0, max=100),
        cli_neo_precoce_sai=fake.random_int(min=0, max=100),
        cli_neo_precoce_obitos=fake.random_int(min=0, max=100),
        cli_neo_precoce_pac_dia=fake.random_int(min=0, max=100),
        cli_neo_tardio_sai=fake.random_int(min=0, max=100),
        cli_neo_tardio_obitos=fake.random_int(min=0, max=100),
        cli_neo_tardio_pac_dia=fake.random_int(min=0, max=100),
        cli_pedi_sai=fake.random_int(min=0, max=100),
        cli_pedi_obitos=fake.random_int(min=0, max=100),
        cli_pedi_pac_dia=fake.random_int(min=0, max=100),
        cli_ad_sai=fake.random_int(min=0, max=100),
        cli_ad_obitos=fake.random_int(min=0, max=100),
        cli_ad_pac_dia=fake.random_int(min=0, max=100),
        cli_idoso_sai=fake.random_int(min=0, max=100),
        cli_idoso_obitos=fake.random_int(min=0, max=100),
        cli_idoso_pac_dia=fake.random_int(min=0, max=100),
        cir_neo_precoce_sai=fake.random_int(min=0, max=100),
        cir_neo_precoce_obitos=fake.random_int(min=0, max=100),
        cir_neo_precoce_pac_dia=fake.random_int(min=0, max=100),
        cir_neo_tardio_sai=fake.random_int(min=0, max=100),
        cir_neo_tardio_obitos=fake.random_int(min=0, max=100),
        cir_neo_tardio_pac_dia=fake.random_int(min=0, max=100),
        cir_pedi_sai=fake.random_int(min=0, max=100),
        cir_pedi_obitos=fake.random_int(min=0, max=100),
        cir_pedi_pac_dia=fake.random_int(min=0, max=100),
        cir_ad_sai=fake.random_int(min=0, max=100),
        cir_ad_obitos=fake.random_int(min=0, max=100),
        cir_ad_pac_dia=fake.random_int(min=0, max=100),
        cir_idoso_sai=fake.random_int(min=0, max=100),
        cir_idoso_obitos=fake.random_int(min=0, max=100),
        cir_idoso_pac_dia=fake.random_int(min=0, max=100),
        total_pac_emerg=fake.random_int(min=0, max=100),
        total_tempo_perm_emerg_hr=fake.random_int(min=0, max=100),
        pac_emerg_nvl2=fake.random_int(min=0, max=100),
        tempo_total_emerg_nvl2_min=fake.random_int(min=0, max=100),
        pac_emerg_nvl3=fake.random_int(min=0, max=100),
        tempo_total_emerg_nvl3_min=fake.random_int(min=0, max=100),
        total_cir_limpas=fake.random_int(min=0, max=100),
        cir_com_antibiotico=fake.random_int(min=0, max=100),
        total_cir_limpas_ant=fake.random_int(min=0, max=100),
        total_infeccoes=fake.random_int(min=0, max=100),
        ui_neo_cvc_dia=fake.random_int(min=0, max=100),
        ui_neo_infec=fake.random_int(min=0, max=100),
        ui_pedi_cvc_dia=fake.random_int(min=0, max=100),
        ui_pedi_infec=fake.random_int(min=0, max=100),
        ui_ad_cvc_dia=fake.random_int(min=0, max=100),
        ui_ad_infec=fake.random_int(min=0, max=100),
        uti_neo_cvc_dia=fake.random_int(min=0, max=100),
        uti_neo_infec=fake.random_int(min=0, max=100),
        uti_pedi_cvc_dia=fake.random_int(min=0, max=100),
        uti_pedi_infec=fake.random_int(min=0, max=100),
        uti_ad_cvc_dia=fake.random_int(min=0, max=100),
        uti_ad_infec=fake.random_int(min=0, max=100),
        ui_neo_cvd_dia=fake.random_int(min=0, max=100),
        ui_neo_itu=fake.random_int(min=0, max=100),
        ui_pedi_cvd_dia=fake.random_int(min=0, max=100),
        ui_pedi_itu=fake.random_int(min=0, max=100),
        ui_ad_cvd_dia=fake.random_int(min=0, max=100),
        ui_ad_itu=fake.random_int(min=0, max=100),
        uti_neo_cvd_dia=fake.random_int(min=0, max=100),
        uti_neo_itu=fake.random_int(min=0, max=100),
        uti_pedi_cvd_dia=fake.random_int(min=0, max=100),
        uti_pedi_itu=fake.random_int(min=0, max=100),
        uti_ad_cvd_dia=fake.random_int(min=0, max=100),
        uti_ad_itu=fake.random_int(min=0, max=100),
        cli_total_pac=fake.random_int(min=0, max=100),
        cli_profilaxia=fake.random_int(min=0, max=100),
        cir_orto_total_pac=fake.random_int(min=0, max=100),
        cir_orto_prof=fake.random_int(min=0, max=100),
        cir_nao_orto_total_pac=fake.random_int(min=0, max=100),
        cir_nao_orto_prof=fake.random_int(min=0, max=100),
        quedas_com_dano=fake.random_int(min=0, max=100),
        eventos_sentinela=fake.random_int(min=0, max=100),
    )