from sqlalchemy     import Column, Integer
from app.database   import Base

class Metrica(Base):
    __tablename__ = "metricas"

    cnes = Column(Integer, primary_key=True, unique=True, index=True, nullable=False)
    ano = Column(Integer, primary_key=True, unique=True, index=True, nullable=False)
    mes = Column(Integer, primary_key=True, unique=True, index=True, nullable=False)
    partos_vag = Column(Integer, nullable=True)
    partos_ces = Column(Integer, nullable=True)
    cli_sai_ant = Column(Integer, nullable=True)
    cli_reint = Column(Integer, nullable=True)
    cir_sai_ant = Column(Integer, nullable=True)
    cir_reint = Column(Integer, nullable=True)
    pac_dia = Column(Integer, nullable=True)
    pcr_eventos = Column(Integer, nullable=True)
    cli_neo_precoce_sai = Column(Integer, nullable=True)
    cli_neo_precoce_obitos = Column(Integer, nullable=True)
    cli_neo_precoce_pac_dia = Column(Integer, nullable=True)
    cli_neo_tardio_sai = Column(Integer, nullable=True)
    cli_neo_tardio_obitos = Column(Integer, nullable=True)
    cli_neo_tardio_pac_dia = Column(Integer, nullable=True)
    cli_pedi_sai = Column(Integer, nullable=True)
    cli_pedi_obitos = Column(Integer, nullable=True)
    cli_pedi_pac_dia = Column(Integer, nullable=True)
    cli_ad_sai = Column(Integer, nullable=True)
    cli_ad_obitos = Column(Integer, nullable=True)
    cli_ad_pac_dia = Column(Integer, nullable=True)
    cli_idoso_sai = Column(Integer, nullable=True)
    cli_idoso_obitos = Column(Integer, nullable=True)
    cli_idoso_pac_dia = Column(Integer, nullable=True)
    cir_neo_precoce_sai = Column(Integer, nullable=True)
    cir_neo_precoce_obitos = Column(Integer, nullable=True)
    cir_neo_precoce_pac_dia = Column(Integer, nullable=True)
    cir_neo_tardio_sai = Column(Integer, nullable=True)
    cir_neo_tardio_obitos = Column(Integer, nullable=True)
    cir_neo_tardio_pac_dia = Column(Integer, nullable=True)
    cir_pedi_sai = Column(Integer, nullable=True)
    cir_pedi_obitos = Column(Integer, nullable=True)
    cir_pedi_pac_dia = Column(Integer, nullable=True)
    cir_ad_sai = Column(Integer, nullable=True)
    cir_ad_obitos = Column(Integer, nullable=True)
    cir_ad_pac_dia = Column(Integer, nullable=True)
    cir_idoso_sai = Column(Integer, nullable=True)
    cir_idoso_obitos = Column(Integer, nullable=True)
    cir_idoso_pac_dia = Column(Integer, nullable=True)
    total_pac_emerg = Column(Integer, nullable=True)
    total_tempo_perm_emerg_hr = Column(Integer, nullable=True)
    pac_emerg_nvl2 = Column(Integer, nullable=True)
    tempo_total_emerg_nvl2_min = Column(Integer, nullable=True)
    pac_emerg_nvl3 = Column(Integer, nullable=True)
    tempo_total_emerg_nvl3_min = Column(Integer, nullable=True)
    total_cir_limpas = Column(Integer, nullable=True)
    cir_com_antibiotico = Column(Integer, nullable=True)
    total_cir_limpas_ant = Column(Integer, nullable=True)
    total_infeccoes = Column(Integer, nullable=True)
    ui_neo_cvc_dia = Column(Integer, nullable=True)
    ui_neo_infec = Column(Integer, nullable=True)
    ui_pedi_cvc_dia = Column(Integer, nullable=True)
    ui_pedi_infec = Column(Integer, nullable=True)
    ui_ad_cvc_dia = Column(Integer, nullable=True)
    ui_ad_infec = Column(Integer, nullable=True)
    uti_neo_cvc_dia = Column(Integer, nullable=True)
    uti_neo_infec = Column(Integer, nullable=True)
    uti_pedi_cvc_dia = Column(Integer, nullable=True)
    uti_pedi_infec = Column(Integer, nullable=True)
    uti_ad_cvc_dia = Column(Integer, nullable=True)
    uti_ad_infec = Column(Integer, nullable=True)
    ui_neo_cvd_dia = Column(Integer, nullable=True)
    ui_neo_itu = Column(Integer, nullable=True)
    ui_pedi_cvd_dia = Column(Integer, nullable=True)
    ui_pedi_itu = Column(Integer, nullable=True)
    ui_ad_cvd_dia = Column(Integer, nullable=True)
    ui_ad_itu = Column(Integer, nullable=True)
    uti_neo_cvd_dia = Column(Integer, nullable=True)
    uti_neo_itu = Column(Integer, nullable=True)
    uti_pedi_cvd_dia = Column(Integer, nullable=True)
    uti_pedi_itu = Column(Integer, nullable=True)
    uti_ad_cvd_dia = Column(Integer, nullable=True)
    uti_ad_itu = Column(Integer, nullable=True)
    cli_total_pac = Column(Integer, nullable=True)
    cli_profilaxia = Column(Integer, nullable=True)
    cir_orto_total_pac = Column(Integer, nullable=True)
    cir_orto_prof = Column(Integer, nullable=True)
    cir_nao_orto_total_pac = Column(Integer, nullable=True)
    cir_nao_orto_prof = Column(Integer, nullable=True)
    quedas_com_dano = Column(Integer, nullable=True)
    eventos_sentinela = Column(Integer, nullable=True)
  